### ISSUE TITLE
NodeValue not correct timestamp when calling .getValue("key") on Node

### ISSUE THREAD

**Issue by nicolaeschbach** [cyber-geiger/toolbox-storage#37] opened 2022-01-19 14:46 UTC
**Describe the bug**
A Node doesn't return the exact clone of the an NodeValue. The lastModified depends on when called .getValue('key').
And not on when the Value actually was modified last time.

**Environmental information**
- geiger_localstorage 0.6.23

**To Reproduce**
```dart
  test('get NodeValue doesnt return the correct nodeValue lastModified ', () async {
    Node node = NodeImpl(':TestNode', 'testOwner');
    NodeValue value = NodeValueImpl('Key1', 'Value');
    await node.addValue(value);
    // delayed just to show the time difference
    await Future.delayed(Duration(milliseconds: 500));
    NodeValue valueCopy = (await node.getValue("Key1"))!;
    expect(value.lastModified, valueCopy.lastModified);
  });
```

**Expected behavior**
NodeValue should be always the same as long as the value is not modified.

**Comment by martingwerder** [comment] 2022-02-10 18:36
The issue should be fixed in 0.6.25. Can you confirm that the issue is solved from your point of view?

**Comment by luongnv89** [comment] 2022-02-23 09:51
@nicolaeschbach can you confirm?

**Comment by martingwerder** [comment] 2022-02-23 15:25
Closed due to inactivity.

**Closed by martingwerder** 2022-02-23 15:25 UTC
Labels: bug, await confirmation
