### ISSUE TITLE
Search Criteria throws Exception if nodeValuelastModified is set

### ISSUE THREAD

**Issue by nicolaeschbach** [cyber-geiger/toolbox-storage#27] opened 2021-12-02 09:22 UTC
**Describe the bug**
Search criteria throws exception if nodeValuelastModified is set and nodes are searched with the criteria in a controller.
StorageException -> 'nodeValueLastModified is unimplemented'

**Environmental information**
- SKD 2.14.4
-  geiger_localstorage: ^0.6.13

**Expected behavior**
If search nodes by nodeValuelastModified should return nodes or nothing but no exception.

**Comment by nosadaniel** [comment] 2021-12-02 09:24
try using the latest version geiger_localstorage: 0.6.15

**Comment by nicolaeschbach** [comment] 2021-12-02 10:29
> try using the latest version geiger_localstorage: 0.6.15
also don't works... here is my code example:
    StorageController controller = GenericController("testOwner", DummyMapper("testOwner"));
    SearchCriteria criteria = SearchCriteria();
    Node node1 = NodeImpl("Device1UUID", "testOwner", ":Devices");
    await controller.add(node1);
    Future.delayed(Duration(seconds: 1));
    criteria.path = ":";
    criteria.nodeValueLastModified = "00000000008439966987-76648f72-5d9a-4bf8-ac7b-53aa3ef41439";
    await controller.search(criteria);

**Comment by martingwerder** [comment] 2021-12-07 08:50
I can confirm the issue. As the exception outlines there is an implementation gap in the ```SearchCriteria``` class causing the issue. Working on it. Will post a fix most likely today as a new development version on pub.dev

**Comment by martingwerder** [comment] 2021-12-08 10:01
Finally it seems to be fixed. Sorry for the delay. The new release is 0.6.16 on pub.dev. Can you confirm that the issue is gone?

**Comment by nicolaeschbach** [comment] 2021-12-13 06:23
Were there any problems with the release? Unfortunately, only version 0.6.15 can be found on pub.dev.

**Comment by martingwerder** [comment] 2021-12-13 09:12
Pushed now as 0.6.17 to pub.dev.

 

Von: nicolaeschbach ***@***.***> 
Gesendet: Montag, 13. Dezember 2021 07:24
An: cyber-geiger/toolbox-storage ***@***.***>
Cc: Martin Gwerder ***@***.***>; Comment
***@***.***>
Betreff: Re: [cyber-geiger/toolbox-storage] Search Criteria throws Exception
if nodeValuelastModified is set (Issue #27)

 

Were there any problems with the release? Unfortunately, only version 0.6.15
can be found on pub.dev.

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fcyber-geiger%2Ftoolbox-storage%2Fissues%2F27%23issuecomment-992146293&da
ta=04%7C01%7Cmartin.gwerder%40fhnw.ch%7C2e6e4bb1402f4e682bec08d9be0119c6%7C9
d1a5fc8321e4101ae63530730711ac2%7C0%7C0%7C637749734207733113%7CUnknown%7CTWF
pbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%
7C3000&sdata=%2FfMjxmq1BkbOvkotRYnMVkQz0AliSFBGpdyC59m0KPQ%3D&reserved=0> ,
or unsubscribe
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAPXCJID4OHZGQ6DWXGGGGILUQWGOHANCNFSM5
JGTEFRA&data=04%7C01%7Cmartin.gwerder%40fhnw.ch%7C2e6e4bb1402f4e682bec08d9be
0119c6%7C9d1a5fc8321e4101ae63530730711ac2%7C0%7C0%7C637749734207733113%7CUnk
nown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXV
CI6Mn0%3D%7C3000&sdata=5aXLDjLfW%2BrzQvpgwafQZaKcaEbbc%2F6Dv0g4LBqA4uI%3D&re
served=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.appl
e.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%
26pt%3D524675&data=04%7C01%7Cmartin.gwerder%40fhnw.ch%7C2e6e4bb1402f4e682bec
08d9be0119c6%7C9d1a5fc8321e4101ae63530730711ac2%7C0%7C0%7C637749734207733113
%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWw
iLCJXVCI6Mn0%3D%7C3000&sdata=%2FFYYuHUOv6JpIbQR12rY5fwcWe6%2BRgWhIDWmH1e%2BI
nE%3D&reserved=0>  or Android.
<https://github.com/notifications/beacon/APXCJIAWMCZWIUA7I5UD3RLUQWGOHA5CNFS
M5JGTEFRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHMRPG5I
.gif>

**Comment by martingwerder** [comment] 2021-12-17 13:16
Fixed in 0.6.20. Are you able to confirm?

**Comment by nicolaeschbach** [comment] 2021-12-26 11:17
Works now! Thanks

**Closed** 2021-12-27 09:39 UTC
Labels: bug, await confirmation
