### ISSUE TITLE
Error when retrieving Node using geiger_localStorage 0.6.0

### ISSUE THREAD

**Issue by nosadaniel** [cyber-geiger/toolbox-storage#18] opened 2021-11-14 12:40 UTC
**Describe the bug**
StorageException occurs while trying to retrieve a node that is stored in the localstorage, but the same sample code(without async/await) works perfectly in geiger_localStorage version 0.5.6

**Environmental information**
geiger_localstorage 0.6.0
dart version : 2.14

**To Reproduce**
```
import 'package:geiger_localstorage/geiger_localstorage.dart';

void main() async{
  //initialize database
  StorageController _storageController =
      GenericController("Example", SqliteMapper("./example.db"));

Future<void> setGlobalThreatsNode() async {
    List<String> threats = ["phishing", "malware"];
    List<String> threatid = ["t1", "t2"];
    try {
      for (int i = 0; i < threats.length; i++) {
        Node _node =
            await _storageController.get(':Global:threats:${threatid[i]}');
        //create a NodeValue
        NodeValue threatNodeValueName = NodeValueImpl("name", threats[i]);
        await _node.addOrUpdateValue(threatNodeValueName);
        await _storageController.update(_node);
      }
    } on StorageException {
      //log(":Global:threats not found");
      Node threatsNode = NodeImpl("threats", ":Global");
      await _storageController.addOrUpdate(threatsNode);

      for (int i = 0; i < threats.length; i++) {
        Node threatIdNode = NodeImpl("${threatid[i]}", ":Global:threats");
        //create :Global:threats:$threatId
        await _storageController.addOrUpdate(threatIdNode);
        //create a NodeValue
        NodeValue threatNodeValueName = NodeValueImpl("name", threats[i]);
        await threatIdNode.addOrUpdateValue(threatNodeValueName);
        await _storageController.update(threatIdNode);
      }
    }
  }

  Future<List<String>> getThreats({String language: "en"}) async {
    List<String> t = [];
    try {
      Node _node = await _storageController.get(":Global:threats");

      //return _node!.getChildNodesCsv();
      for (String threatId
          in await _node.getChildNodesCsv().then((value) => value.split(','))) {
        Node threatNode =
            await _storageController.get(":Global:threats:$threatId");

        t.add(await threatNode
            .getValue("name")
            .then((value) => value!.getValue(language)!));
      }
    } on StorageException {
      rethrow;
    }
    return t;
  }

  getListThreat() async {
    await setGlobalThreatsNode();
    print("{await getThreats()}");
  }

  print("Global Threats: ${await getListThreat()}");

}


```
**Expected behavior**
show => Global threats: ["phishing","malware"]

**Screenshots**
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/33612084/141681259-81507770-5d8d-425a-8099-e2e31e5a7194.png">

**Additional context**
Upon further investigation, I found out the node and node value was actually created and value store in the database.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/33612084/141681349-0daf352a-85c0-42b7-8ac4-d62e69354c16.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/33612084/141681365-f8ea491c-6c67-496a-a1e6-ab77783aa267.png">

**Comment by martingwerder** [comment] 2021-11-18 14:00
This was addressed in 0.6.3. Can you confirm that the issue is gone?

**Comment by nosadaniel** [comment] 2021-11-18 15:13
issue still persists

**Comment by martingwerder** [comment] 2021-11-19 14:36
I am not sure. The provided code is full of bugs and it is hard to tell from the codewhat the intention was. I tried to correct the code in your intention and added it to the user tests. Here is what I spotted as errors:

- In several locations you adress the NodeImpl with a parent path as "owner" (causes uncaught exceptions)
- getListThreat does not retur a value and yet you are looking for it

I tried to reimplement your code while still maintaining your structure. Have a look at the user_test.dart. Look for Issue #19. You should find two versions. Your debugged and a more compact version.

Does that help you to get further?

**Comment by nosadaniel** [comment] 2021-11-19 15:12
My apology about the wrong description  of the the expected behaviour.  

your test code works but an empty list was returned.

**Comment by martingwerder** [comment] 2021-11-19 16:03
It helps reading the Changelog (especially when anouncing a breaking change). The second note is however right. There was a related issue when evaluating search criteria in conjunction with the sqlite mapper only. I pushed a new release which should fix the newly discovered bug in the shortened code.

**Closed** 2021-11-19 16:03 UTC
Labels: bug
